# for what versions are available, see:
# https://github.com/travis-ci/travis-cookbooks/blob/master/ci_environment/perlbrew/attributes/multi.rb
language: perl
perl:
    #- dev
    - "blead"
    #- stable
    - "5.20"
    - "5.18"
    - "5.16"
    - "5.14"
    - "5.12"
    - "5.10"
    - "5.8"
    - "5.8.3"
    - "5.8.5"
    - "5.8.8"
env:
  global:
    - TEST_PARTITIONS=4
    - RELEASE_TESTING=1
matrix:
  include:
    - perl: "5.20"
      env: COVERAGE=1 TEST_PARTITION=1
    - perl: "5.20"
      env: COVERAGE=1 TEST_PARTITION=2
    - perl: "5.20"
      env: COVERAGE=1 TEST_PARTITION=3
    - perl: "5.20"
      env: COVERAGE=1 TEST_PARTITION=4
  allow_failures:
    - perl: "5.20"
      env: COVERAGE=1 TEST_PARTITION=1
    - perl: "5.20"
      env: COVERAGE=1 TEST_PARTITION=2
    - perl: "5.20"
      env: COVERAGE=1 TEST_PARTITION=3
    - perl: "5.20"
      env: COVERAGE=1 TEST_PARTITION=4
before_install:
  - git clone git://github.com/haarg/perl-travis-helper ~/perl-travis-helper
  - source ~/perl-travis-helper/init
  - build-perl
  - perl -V
  - build-dist
  - cd $BUILD_DIR
  - cat META.yml
  - cat META.json
  - cat Makefile.PL
install:
  - cpan-install ExtUtils::MakeMaker~6.68 --deps
  - cpan-install --coverage
before_script:
  - coverage-setup
script:
  - perl Makefile.PL
  - make
  - prove -b -r -s -j$(test-jobs) $(test-files)
after_success:
  - coverage-report
